remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: Braided vs Meandering river Classifiers
description: Some basic examples of classifiers hosted by Hugging Face api

author:
  name: Larisa M
